### ISSUE TITLE
Website URL should be added to About

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/oneAPI-for-SciPy#3]
https://oleksandr-pavlyk.github.io/oneAPI-for-SciPy/

**Comment by oleksandr-pavlyk** [comment]
This is done by specifying ``[menu.main]]`` section in `config.toml`. Example in https://github.com/Xceptance/xlt-documentation/blob/master/config.toml#L181

I am pushing this change to my branch.

**Comment by oleksandr-pavlyk** [comment]
This was to add the URL to "About" section of this repo. 

For some reason the website field in settings is grayed out.

![Screen-shot of About section settings UI](https://user-images.githubusercontent.com/21087696/174391193-28f22cd5-5af0-42fb-bae0-13b1c690a244.png)

It is not gray in `IntelPython/dpctl`, for example. I am not sure how to influence this behavior.

**Comment by oleksandr-pavlyk** [comment]
URL added now.
